export const en = {
  appName: 'Tu Ruta Honduras',
  tagline: 'Your smart mobility guide',
  slogan: 'Travel smart across Honduras',

  home: 'Home',
  search: 'Search',
  trips: 'My Trips',
  profile: 'Profile',
  admin: 'Admin',

  searchTitle: 'Plan your trip',
  origin: 'Origin',
  destination: 'Destination',
  date: 'Date',
  passengers: 'Passengers',
  searchButton: 'Search Routes',
  whereTo: 'Where are you going?',
  whereFrom: 'Where are you from?',
  myLocation: 'My location',

  routesFound: 'routes found',
  noRoutesFound: 'No routes found',
  noRoutesMessage: 'Try different cities or dates',
  cheapest: 'Cheapest',
  fastest: 'Fastest',
  bestOption: 'Best Option',
  selectRoute: 'Select',
  viewDetails: 'View Details',

  departure: 'Departure',
  arrival: 'Arrival',
  duration: 'Duration',
  price: 'Price',
  stops: 'Stops',
  frequency: 'Frequency',
  schedule: 'Schedule',
  bookNow: 'Book Now',
  company: 'Company',
  distance: 'Distance',

  bookTrip: 'Book Trip',
  travelDate: 'Travel date',
  travelTime: 'Departure time',
  numPassengers: 'Number of passengers',
  paymentMethod: 'Payment method',
  cardPayment: 'Credit/Debit card',
  cashPayment: 'Cash',
  transferPayment: 'Bank transfer',
  confirmBooking: 'Confirm Booking',
  bookingConfirmed: 'Booking Confirmed',
  bookingSuccess: 'Your trip has been booked successfully',
  totalPrice: 'Total price',

  cardNumber: 'Card number',
  cardName: 'Name on card',
  expiryDate: 'Expiry date',
  cvv: 'CVV',
  processPayment: 'Process Payment',

  login: 'Login',
  register: 'Register',
  logout: 'Logout',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm password',
  fullName: 'Full name',
  phone: 'Phone',
  forgotPassword: 'Forgot your password?',
  resetPassword: 'Reset Password',
  loginWithGoogle: 'Continue with Google',
  noAccount: "Don't have an account?",
  hasAccount: 'Already have an account?',
  signUpNow: 'Sign up now',
  loginNow: 'Log in',

  myProfile: 'My Profile',
  editProfile: 'Edit Profile',
  saveChanges: 'Save Changes',
  language: 'Language',
  location: 'Location',
  changePhoto: 'Change Photo',
  myBookings: 'My Bookings',
  emergencyContacts: 'Emergency Contacts',
  addContact: 'Add Contact',
  relationship: 'Relationship',

  shareTrip: 'Share Trip',
  shareLocation: 'Share Location',
  emergency: 'Emergency',
  callPolice: 'Call Police',
  callAmbulance: 'Call Ambulance',
  callFireDept: 'Call Fire Dept',
  safetyTitle: 'Your Safety',

  rateTrip: 'Rate Trip',
  writeReview: 'Write a review',
  submitReview: 'Submit Review',
  reviews: 'Reviews',
  noReviews: 'No reviews yet',

  adminPanel: 'Admin Panel',
  companies: 'Companies',
  routes: 'Routes',
  users: 'Users',
  bookings: 'Bookings',
  statistics: 'Statistics',
  reports: 'Reports',
  addCompany: 'Add Company',
  addRoute: 'Add Route',
  totalUsers: 'Total Users',
  totalBookings: 'Total Bookings',
  totalRevenue: 'Total Revenue',
  activeRoutes: 'Active Routes',

  companiesTitle: 'Transport Companies',
  viewRoutes: 'View Routes',
  callCompany: 'Call',
  busType: 'Bus',
  minibusType: 'Minibus',
  taxiType: 'Taxi',
  shuttleType: 'Shuttle',
  internationalType: 'International',

  mapView: 'Map View',
  currentLocation: 'My Location',
  recenter: 'Recenter',

  loading: 'Loading...',
  error: 'Error',
  retry: 'Retry',
  cancel: 'Cancel',
  confirm: 'Confirm',
  close: 'Close',
  back: 'Back',
  next: 'Next',
  save: 'Save',
  delete: 'Delete',
  edit: 'Edit',
  active: 'Active',
  inactive: 'Inactive',
  yes: 'Yes',
  no: 'No',
  hours: 'hours',
  minutes: 'minutes',
  km: 'km',
  hour: 'hour',
  minute: 'minute',

  popularRoutes: 'Popular Routes',
  allCities: 'All Cities',

  about: 'About',
  contact: 'Contact',
  terms: 'Terms',
  privacy: 'Privacy',
  help: 'Help',
};
