export const fr = {
  appName: 'Tu Ruta Honduras',
  tagline: 'Votre guide de mobilité intelligente',
  slogan: 'Voyagez intelligemment au Honduras',
  home: 'Accueil', search: 'Rechercher', trips: 'Mes Voyages', profile: 'Profil', admin: 'Admin',
  searchTitle: 'Planifiez votre voyage', origin: 'Origine', destination: 'Destination', date: 'Date', passengers: 'Passagers',
  searchButton: 'Chercher des Itinéraires', whereTo: 'Où allez-vous?', whereFrom: "D'où partez-vous?", myLocation: 'Ma position',
  routesFound: 'itinéraires trouvés', noRoutesFound: 'Aucun itinéraire trouvé', noRoutesMessage: "Essayez d'autres villes ou dates",
  cheapest: 'Moins Cher', fastest: 'Plus Rapide', bestOption: 'Meilleure Option', selectRoute: 'Sélectionner', viewDetails: 'Voir Détails',
  departure: 'Départ', arrival: 'Arrivée', duration: 'Durée', price: 'Prix', stops: 'Arrêts',
  frequency: 'Fréquence', schedule: 'Horaire', bookNow: 'Réserver Maintenant', company: 'Entreprise', distance: 'Distance',
  bookTrip: 'Réserver le Voyage', travelDate: 'Date de voyage', travelTime: 'Heure de départ', numPassengers: 'Nombre de passagers',
  paymentMethod: 'Mode de paiement', cardPayment: 'Carte bancaire', cashPayment: 'Espèces', transferPayment: 'Virement',
  confirmBooking: 'Confirmer la Réservation', bookingConfirmed: 'Réservation Confirmée', bookingSuccess: 'Votre voyage a été réservé avec succès', totalPrice: 'Prix total',
  cardNumber: 'Numéro de carte', cardName: 'Nom sur la carte', expiryDate: "Date d'expiration", cvv: 'CVV', processPayment: 'Traiter le Paiement',
  login: 'Se Connecter', register: "S'inscrire", logout: 'Se Déconnecter', email: 'E-mail', password: 'Mot de passe',
  confirmPassword: 'Confirmer le mot de passe', fullName: 'Nom complet', phone: 'Téléphone',
  forgotPassword: 'Mot de passe oublié?', resetPassword: 'Réinitialiser', loginWithGoogle: 'Continuer avec Google',
  noAccount: "Pas de compte?", hasAccount: 'Vous avez déjà un compte?', signUpNow: "S'inscrire", loginNow: 'Se connecter',
  myProfile: 'Mon Profil', editProfile: 'Modifier le Profil', saveChanges: 'Enregistrer', language: 'Langue',
  location: 'Lieu', changePhoto: 'Changer Photo', myBookings: 'Mes Réservations', emergencyContacts: "Contacts d'Urgence",
  addContact: 'Ajouter Contact', relationship: 'Relation',
  shareTrip: 'Partager le Voyage', shareLocation: 'Partager Position', emergency: 'Urgence',
  callPolice: 'Appeler Police', callAmbulance: 'Appeler Ambulance', callFireDept: 'Appeler Pompiers', safetyTitle: 'Votre Sécurité',
  rateTrip: 'Évaluer le Voyage', writeReview: 'Écrire un avis', submitReview: 'Envoyer', reviews: 'Avis', noReviews: 'Aucun avis',
  adminPanel: "Panneau d'Administration", companies: 'Entreprises', routes: 'Itinéraires', users: 'Utilisateurs', bookings: 'Réservations',
  statistics: 'Statistiques', reports: 'Rapports', addCompany: 'Ajouter Entreprise', addRoute: 'Ajouter Itinéraire',
  totalUsers: "Total d'Utilisateurs", totalBookings: 'Total Réservations', totalRevenue: 'Revenus Totaux', activeRoutes: 'Itinéraires Actifs',
  companiesTitle: 'Entreprises de Transport', viewRoutes: 'Voir Itinéraires', callCompany: 'Appeler',
  busType: 'Bus', minibusType: 'Minibus', taxiType: 'Taxi', shuttleType: 'Navette', internationalType: 'International',
  mapView: 'Carte', currentLocation: 'Ma Position', recenter: 'Recentrer',
  loading: 'Chargement...', error: 'Erreur', retry: 'Réessayer', cancel: 'Annuler', confirm: 'Confirmer',
  close: 'Fermer', back: 'Retour', next: 'Suivant', save: 'Enregistrer', delete: 'Supprimer', edit: 'Modifier',
  active: 'Actif', inactive: 'Inactif', yes: 'Oui', no: 'Non',
  hours: 'heures', minutes: 'minutes', km: 'km', hour: 'heure', minute: 'minute',
  popularRoutes: 'Itinéraires Populaires', allCities: 'Toutes les Villes',
  about: 'À Propos', contact: 'Contact', terms: 'Conditions', privacy: 'Confidentialité', help: 'Aide',
};
