export const pt = {
  appName: 'Tu Ruta Honduras',
  tagline: 'Seu guia de mobilidade inteligente',
  slogan: 'Viaje com inteligência por Honduras',
  home: 'Início', search: 'Pesquisar', trips: 'Minhas Viagens', profile: 'Perfil', admin: 'Admin',
  searchTitle: 'Planeje sua viagem', origin: 'Origem', destination: 'Destino', date: 'Data', passengers: 'Passageiros',
  searchButton: 'Buscar Rotas', whereTo: 'Para onde você vai?', whereFrom: 'De onde você parte?', myLocation: 'Minha localização',
  routesFound: 'rotas encontradas', noRoutesFound: 'Nenhuma rota encontrada', noRoutesMessage: 'Tente outras cidades ou datas',
  cheapest: 'Mais Barato', fastest: 'Mais Rápido', bestOption: 'Melhor Opção', selectRoute: 'Selecionar', viewDetails: 'Ver Detalhes',
  departure: 'Partida', arrival: 'Chegada', duration: 'Duração', price: 'Preço', stops: 'Paradas',
  frequency: 'Frequência', schedule: 'Horário', bookNow: 'Reservar Agora', company: 'Empresa', distance: 'Distância',
  bookTrip: 'Reservar Viagem', travelDate: 'Data de viagem', travelTime: 'Hora de saída', numPassengers: 'Número de passageiros',
  paymentMethod: 'Método de pagamento', cardPayment: 'Cartão bancário', cashPayment: 'Dinheiro', transferPayment: 'Transferência',
  confirmBooking: 'Confirmar Reserva', bookingConfirmed: 'Reserva Confirmada', bookingSuccess: 'Sua viagem foi reservada com sucesso', totalPrice: 'Preço total',
  cardNumber: 'Número do cartão', cardName: 'Nome no cartão', expiryDate: 'Data de validade', cvv: 'CVV', processPayment: 'Processar Pagamento',
  login: 'Entrar', register: 'Cadastrar', logout: 'Sair', email: 'E-mail', password: 'Senha',
  confirmPassword: 'Confirmar senha', fullName: 'Nome completo', phone: 'Telefone',
  forgotPassword: 'Esqueceu sua senha?', resetPassword: 'Redefinir Senha', loginWithGoogle: 'Continuar com Google',
  noAccount: 'Não tem uma conta?', hasAccount: 'Já tem uma conta?', signUpNow: 'Cadastre-se', loginNow: 'Entrar',
  myProfile: 'Meu Perfil', editProfile: 'Editar Perfil', saveChanges: 'Salvar Alterações', language: 'Idioma',
  location: 'Localização', changePhoto: 'Alterar Foto', myBookings: 'Minhas Reservas', emergencyContacts: 'Contatos de Emergência',
  addContact: 'Adicionar Contato', relationship: 'Relacionamento',
  shareTrip: 'Compartilhar Viagem', shareLocation: 'Compartilhar Localização', emergency: 'Emergência',
  callPolice: 'Ligar para Polícia', callAmbulance: 'Chamar Ambulância', callFireDept: 'Chamar Bombeiros', safetyTitle: 'Sua Segurança',
  rateTrip: 'Avaliar Viagem', writeReview: 'Escreva um comentário', submitReview: 'Enviar Avaliação', reviews: 'Avaliações', noReviews: 'Sem avaliações ainda',
  adminPanel: 'Painel Administrativo', companies: 'Empresas', routes: 'Rotas', users: 'Usuários', bookings: 'Reservas',
  statistics: 'Estatísticas', reports: 'Relatórios', addCompany: 'Adicionar Empresa', addRoute: 'Adicionar Rota',
  totalUsers: 'Total de Usuários', totalBookings: 'Total de Reservas', totalRevenue: 'Receita Total', activeRoutes: 'Rotas Ativas',
  companiesTitle: 'Empresas de Transporte', viewRoutes: 'Ver Rotas', callCompany: 'Ligar',
  busType: 'Ônibus', minibusType: 'Micro-ônibus', taxiType: 'Táxi', shuttleType: 'Shuttle', internationalType: 'Internacional',
  mapView: 'Mapa', currentLocation: 'Minha Localização', recenter: 'Centralizar',
  loading: 'Carregando...', error: 'Erro', retry: 'Tentar novamente', cancel: 'Cancelar', confirm: 'Confirmar',
  close: 'Fechar', back: 'Voltar', next: 'Próximo', save: 'Salvar', delete: 'Excluir', edit: 'Editar',
  active: 'Ativo', inactive: 'Inativo', yes: 'Sim', no: 'Não',
  hours: 'horas', minutes: 'minutos', km: 'km', hour: 'hora', minute: 'minuto',
  popularRoutes: 'Rotas Populares', allCities: 'Todas as Cidades',
  about: 'Sobre', contact: 'Contato', terms: 'Termos', privacy: 'Privacidade', help: 'Ajuda',
};
